/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = (import.meta as any).env?.VITE_SUPABASE_PROJECT_ID || "tnaoasoznlzmbkennoiy"
export const publicAnonKey = (import.meta as any).env?.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRuYW9hc296bmx6bWJrZW5ub2l5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ3MTc5OTYsImV4cCI6MjA5MDI5Mzk5Nn0.HabEUgqqzrGx7ng76dnaeKLLF_dvVTek8djPZOmYzU0"